# Generated by Django 4.2.27 on 2026-01-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('fashion', 'Fashion'), ('electronics', 'Electronics')], default='grocery', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage (set by master admin)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Business description for storefront'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Store is open for business'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by master admin'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True, help_text='Business logo URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total commission earned by platform', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lifetime sales for this business', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Business/Store Name', max_length=255),
        ),
    ]
