# Generated by Django 4.2.27 on 2026-01-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('delivery', '0002_deliverypersonnel_address_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone/District for shipping fee calculation', max_length=50),
        ),
        migrations.CreateModel(
            name='ShippingFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, help_text='Zone/District name (e.g., "Downtown", "Suburbs")', max_length=50)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=0, help_text='Additional fee per kilometer', max_digits=10)),
                ('min_distance', models.IntegerField(default=0, help_text='Minimum distance (km) for this rule')),
                ('max_distance', models.IntegerField(default=1000, help_text='Maximum distance (km) for this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
