# Generated by Django 4.2.27 on 2026-01-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('sales', 'Sales Tax'), ('service', 'Service Tax'), ('other', 'Other')], default='vat', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 15.00 for 15%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, help_text='VAT/tax collected from sales', max_digits=15)),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0, help_text='Tax paid on expenses', max_digits=15)),
                ('net_tax_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Profit & Loss Report',
                'verbose_name_plural': 'Profit & Loss Reports',
                'ordering': ['-generated_at'],
                'unique_together': {('tenant', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cogs', 'Cost of Goods Sold'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries & Wages'), ('marketing', 'Marketing'), ('equipment', 'Equipment'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Fees'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Amount + Tax', max_digits=12)),
                ('expense_date', models.DateField(help_text='Date when expense was incurred')),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'expense_date'], name='finance_exp_tenant__3c8047_idx'), models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx')],
            },
        ),
    ]
