# Generated by Django 4.2.27 on 2026-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_barcode_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Product category (e.g., Grocery, Electronics, Pharmacy)', max_length=100),
        ),
    ]
