# Generated by Django 4.2.27 on 2026-01-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('visa_mastercard', 'Visa/Mastercard'), ('apple_pay', 'Apple Pay'), ('samsung_pay', 'Samsung Pay'), ('google_pay', 'Google Pay'), ('wallet', 'Digital Wallet'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('mada', 'MADA (Saudi Arabia)'), ('stc_pay', 'STC Pay'), ('urpay', 'urPay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
